update env

diff --git a/.github/workflows/ios_auto.yml b/.github/workflows/ios_auto.yml
--- a/.github/workflows/ios_auto.yml
+++ b/.github/workflows/ios_auto.yml
@@ -12,6 +12,9 @@ jobs:
   test:
     name: iOS Automation Test
     runs-on: macos-latest
+    env:
+      IOS_VERSION: 16.2
+      IOS_UDID: "6E16567A-DE1B-4B4E-A1A0-F5FBD6B720B1"
 
     steps:
       - name: Set up Homebrew
@@ -29,35 +32,35 @@ jobs:
         with:
           model: "${{ vars.IOS_DEVICE }}"
 
-      - name: Get device information
-        id: device-info
-        run: |
-          DEVICE_INFO=$(xcrun simctl list --json devices available)
-          echo "Device Info: $DEVICE_INFO"
-          DEVICE_VERSION=$(echo "$DEVICE_INFO" | jq -r '.devices | to_entries[] | select(.key | contains("iOS")) | .value[] | select(.model == "${{ vars.IOS_DEVICE }}") | .name')
-          UDID=$(echo "$DEVICE_INFO" | jq -r '.devices | to_entries[] | select(.key | contains("iOS")) | .value[] | select(.model == "${{ vars.IOS_DEVICE }}") | .udid')
+      # - name: Get device information
+      #   id: device-info
+      #   run: |
+      #     DEVICE_INFO=$(xcrun simctl list --json devices available)
+      #     echo "Device Info: $DEVICE_INFO"
+      #     DEVICE_VERSION=$(echo "$DEVICE_INFO" | jq -r '.devices | to_entries[] | select(.key | contains("iOS")) | .value[] | select(.model == "${{ vars.IOS_DEVICE }}") | .name')
+      #     UDID=$(echo "$DEVICE_INFO" | jq -r '.devices | to_entries[] | select(.key | contains("iOS")) | .value[] | select(.model == "${{ vars.IOS_DEVICE }}") | .udid')
 
-          if [[ -z "$DEVICE_VERSION" ]]; then
-            echo "Unable to find device version."
-            exit 1
-          fi
+      #     if [[ -z "$DEVICE_VERSION" ]]; then
+      #       echo "Unable to find device version."
+      #       exit 1
+      #     fi
 
-          if [[ -z "$UDID" ]]; then
-            echo "Unable to find device UDID."
-            exit 1
-          fi
+      #     if [[ -z "$UDID" ]]; then
+      #       echo "Unable to find device UDID."
+      #       exit 1
+      #     fi
 
-          echo "Device Version: $DEVICE_VERSION"
-          echo "UDID: $UDID"
+      #     echo "Device Version: $DEVICE_VERSION"
+      #     echo "UDID: $UDID"
 
-        env:
-          DEVICE_VERSION: ${{ steps.device-info.outputs.device_version }}
-          UDID: ${{ steps.device-info.outputs.udid }}
+      #   env:
+      #     DEVICE_VERSION: ${{ steps.device-info.outputs.device_version }}
+      #     UDID: ${{ steps.device-info.outputs.udid }}
 
-      - name: Set device version and UDID as environment variables
-        run: |
-          echo "DEVICE_VERSION=${DEVICE_VERSION}" >> $GITHUB_ENV
-          echo "UDID=${UDID}" >> $GITHUB_ENV
+      # - name: Set device version and UDID as environment variables
+      #   run: |
+      #     echo "DEVICE_VERSION=${DEVICE_VERSION}" >> $GITHUB_ENV
+      #     echo "UDID=${UDID}" >> $GITHUB_ENV
 
       - name: Set up Python
         uses: actions/setup-python@v4
